### ISSUE TITLE
hota指标

### ISSUE THREAD

**Issue by congyao123456** [noahcao/OC_SORT#104]
你好跟着你的readme在mot17数据集上测试，只得到 IDF1   IDP   IDR  Rcll  Prcn  GT  MT  PT ML   FP   FN IDs   FM  MOTA  MOTP IDt IDa IDm num_objects这些指标，请问如何获得hota指标？

**Comment by YN-Yang** [comment]
Have you resolved this issue? @congyao123456

**Comment by YN-Yang** [comment]
you can follow 'https://github.com/DanceTrack/DanceTrack/tree/main/TrackEval' to get HOTA metrics. @congyao123456
