### ISSUE TITLE
Implementing UKF or adding Acceleration to the Motion Model

### ISSUE THREAD

**Issue by dead-beaf** [noahcao/OC_SORT#108]
I'm thinking about how the implementation of an Unscented Kalman Filter / the addition of acceleration to the motion model may improve results from OC-SORT. @noahcao Do you have any thoughts on this, or have you investigated the usage of UKF or even EKF?
I see in the paper you mention that particle-filter methods are typically not implemented due to exponential computing costs, however, for a tracker like OC SORT that already operates at several hundred FPS do you think it is worth exploring the usage of something like UKF?

**Comment by noahcao** [comment]
You can add the acceleration as an extra term in the state representation. It improves the performance a little bit on certain datasets. But per my experience, it dose not make fundamentally and generalizably significant performance improvement. The noise (variance) of the acceleration is expected to be more significant than velocity (and of course, ven more than position), especially on high-frame-rate videos. This can have a negative impact on the performance.  

There is a conceptual difference bewteen KF and EKF/UKF to point out: UKF/EKF does not rely on the linear motion assumption. Therefore, it might not be what the modifications of OC-SORT over SORT are designed for. For example, OCM comes from a linear motion assumption and its gap between the real trajectories as tracked. For UKF/EKF, it might be tricky to determine how to adapt it or whether we need to remove it. In general, I suggest studying the UKF/EKF by analyzing the failure cases. If the failures come from the gap between the pattern of real trajectory and the tracker assumption, of course we should do something. I just doubt what OC-SORT proposes can be, confidently, directly migrated.
