### ISSUE TITLE
speed_direction_batch() at the beginning of tracking

### ISSUE THREAD

**Issue by HanGuangXin** [noahcao/OC_SORT#11]
Thanks for the amazing work!

But I find something confusing when using oc-sort. At the beginning of tracking (like frame 2), the input variables of function `speed_direction_batch()` is `detections` and `previous_obs`. 

But the `previous_obs` is [-1, -1, -1, -1, -1], which I don't think is normal.

Is it an issue, or I should just ignore it?

**Comment by HanGuangXin** [comment]
I had a thought. When the `previous_obs` is [-1, -1, -1, -1, -1], the `velocities` is 0, which makes `diff_angle_cos` to be 0. So it doesn't matter.

Am I right?

**Comment by noahcao** [comment]
Yes, you are right. The [-1,-1,-1,-1,-1] is just a dumb (and ugly) placeholder for the beginning when no historical observation is available yet, having no influence over the association matrix. 

I apologize for the confusion. I should have made it a better way. Stay tuned for a better version here or in mmtracking. Or, please feel free to make PR for that!

**Comment by HanGuangXin** [comment]
Thanks for the reply!
If it is possible, could you please update codes here (and in mmtracking). I used mmdetection for a while, and I think it makes codes harder to understand due to its modular design.

That's just my little wish, don't take it so serious.

**Comment by noahcao** [comment]
Yes. I will definitely update this. The current released version is a timely and primary version. The coming version should be more complete and well-formed.

**Comment by HanGuangXin** [comment]
Thanks in advance! OC-SORT is truly awesome!
