### ISSUE TITLE
Integrated OC_SORT Algorithm into X-AnyLabeling for Enhanced Annotation

### ISSUE THREAD

**Issue by CVHub520** [noahcao/OC_SORT#110]
Hello,

I've integrated the latest OC_SORT algorithm into [X-AnyLabeling](https://github.com/CVHub520/X-AnyLabeling), a high-level automatic annotation tool with multiple state-of-the-art model integrations. I wanted to bring this to your attention so that others can explore and experience the integration.

Great work on OC_SORT!

Best regards,
CVHub

**Comment by noahcao** [comment]
Thanks for your work and contribution with OC-SORT! @CVHub520
