### ISSUE TITLE
Question about Angle Difference Cost Computation.

### ISSUE THREAD

**Issue by Ali96528** [noahcao/OC_SORT#111]
hello, @noahcao :
I don't quite understand the meaning of a part of the code about angle calculation,could you give me some tips?

here is the code about angle difference computation:
`Y, X = speed_direction_batch(detections, previous_obs)
inertia_Y, inertia_X = velocities[:,0], velocities[:,1]
inertia_Y = np.repeat(inertia_Y[:, np.newaxis], Y.shape[1], axis=1)
inertia_X = np.repeat(inertia_X[:, np.newaxis], X.shape[1], axis=1)
diff_angle_cos = inertia_X * X + inertia_Y * Y
diff_angle_cos = np.clip(diff_angle_cos, a_min=-1, a_max=1)
diff_angle = np.arccos(diff_angle_cos)
diff_angle = (np.pi /2.0 - np.abs(diff_angle)) / np.pi`

It seems that you have calculated the radian angle throgh the code "diff_angle = np.arccos(diff_angle_cos)". 
So what does this line of code "diff_angle = (np.pi /2.0 - np.abs(diff_angle)) / np.pi" do? Why do we need to do this?

Thank you for replying.

**Comment by noahcao** [comment]
`diff_angle = (np.pi /2.0 - np.abs(diff_angle)) / np.pi` is to centerized and normalized the angle difference calculated. And also, we would like to make sure that the same angle difference in either clockwise and counter-clockwise is regarded the same.
