### ISSUE TITLE
do you use the linear interpolation when you compared your method with other SOTA methods ?

### ISSUE THREAD

**Issue by WesLee88524** [noahcao/OC_SORT#116]
Hi, do you use the linear interpolation when you compared your method with other SOTA methods as Tables 1 and 2 show?
![截屏2024-01-03 11 50 39](https://github.com/noahcao/OC_SORT/assets/25226447/731796a0-7956-4315-a9ca-f71cef32f2e1)

**Comment by noahcao** [comment]
yes, as mentioned in the Section 5.2: 

> We inherit the linear interpolation on the two datasets as baseline methods for a fair comparison
