### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by panwpalo** [noahcao/OC_SORT#121]
How does the implementation in this repository compares to the MMTracking implementation? Does MMtracking has a lower latency during inference?

**Comment by panwpalo** [comment]
I compared the inference time on cpu with the MMtracking. The MMtracking is very slow but at leas it runs at almost 1 fps but the implementation in this repo takes for ever.

**Comment by panwpalo** [comment]
@noahcao ^^

**Comment by noahcao** [comment]
From my experience, the implementation in mmtracking is slower in most cases as it requires a large codebase and designed for better flexibility. But I don't think it ran as slow as 1fps when I tested it. Can you check the efficiency bottleneck for the mmtracking implementation to make more cues?
