### ISSUE TITLE
which version of gcc used?

### ISSUE THREAD

**Issue by echo-sky** [noahcao/OC_SORT#13]
When I run python setup.py develop, a problem occurs.as:
g++: error: /media/peng/Data/Myproject/Chapter2-Track/code/run/OC_SORT-master/build/temp.linux-x86_64-3.6/media/peng/Data/Myproject/Chapter2-Track/code/run/OC_SORT-master/yolox/layers/csrc/vision.o: No such file or directory
g++: error: /media/peng/Data/Myproject/Chapter2-Track/code/run/OC_SORT-master/build/temp.linux-x86_64-3.6/media/peng/Data/Myproject/Chapter2-Track/code/run/OC_SORT-master/yolox/layers/csrc/cocoeval/cocoeval.o: No such file or directory
error: command 'g++' failed with exit status 1

I used gcc 5.4 version.
I haven't solved this problem.

**Comment by noahcao** [comment]
Hi,

my version is: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by echo-sky** [comment]
Hello, I updated gcc to version 7..5
the same problem accurs.
Could you please help me, which maybe the reason that caused it.
Many thanks.

**Comment by noahcao** [comment]
Hi, I tried to look into this issue, but got no idea from the OC_SORT side.

I believe that should be an issue from YOLOX, for which you can find a same issue reported [here](https://github.com/Megvii-BaseDetection/YOLOX/issues/732). I would recommend you to look into the requirement of YOLOX first and check if there is any incompatibility.

**Comment by noahcao** [comment]
I am closing this issue as this issue is probably related to YOLOX instead of OC-SORT repo.
