### ISSUE TITLE
used in DeepSort  

### ISSUE THREAD

**Issue by zyiyid** [noahcao/OC_SORT#15]
Have you tried using your new Kalman filter in DeepSort?

**Comment by noahcao** [comment]
No, I haven't systemically tried that. You can try that easily by combining the DeepSORT, which is also provided, and corresponding alternative modules from OC-SORT. It would be wonderful if you can share some results here.

**Comment by noahcao** [comment]
We recently have an improved version of combining OC-SORT + Deep SORT, which we name as Deep OC-SORT. You can check the details [here](https://github.com/GerardMaggiolino/Deep-OC-SORT).
