### ISSUE TITLE
Multi-class tracking

### ISSUE THREAD

**Issue by oliverwang15** [noahcao/OC_SORT#16]
Hi, your work is wonderful! I'm trying to use it in my project. But in my project, I need to track 7 kinds of  viechles in traffic carema videos. But it seems that [the update method of OCSort class](https://github.com/noahcao/OC_SORT/blob/b43384f28fbe78910064efbc9189a569128a1b89/trackers/ocsort_tracker/ocsort.py#L192) doesn't care about the class. So is there any way that I can get the tracking result with classes or how I can change your code to manage that. Thanks!

**Comment by noahcao** [comment]
As OC-SORT has supported KITTI, on which there are more than one category of interest, I have supported multi-class tracking. See [here](https://github.com/noahcao/OC_SORT/blob/b43384f28fbe78910064efbc9189a569128a1b89/trackers/ocsort_tracker/ocsort.py#L356) for reference. The basic idea is: when the category of a detection and an existing track are different, never associate them (by giving a extremely high cost).

**Comment by oliverwang15** [comment]
Ok. Thanks a lot!

**Comment by CaptainEven** [comment]
@oliverwang15 Please refer to this issue #33
