### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by iTruffle** [noahcao/OC_SORT#17]
I got errors like these:
![image](https://user-images.githubusercontent.com/80766557/164470076-b245160a-7e32-441a-bf98-e7551a60861e.png)

my environment like this:
pytorch==1.7.1    python==3.8    cuda==11.0

and i run this:
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch

**Comment by noahcao** [comment]
Please check if you can run pytorch on your "cuda" device or not:

torch.cuda.is_available()

**Comment by iTruffle** [comment]
I checked justnow, the pytorch is on my 'cuda' device.
![image](https://user-images.githubusercontent.com/80766557/164581500-fb38984a-063a-4df4-a5c5-be061f7ca291.png)

**Comment by noahcao** [comment]
A typical reason causing this issue is the incompatibility  of (1) GPU device (2) CUDA version and (3) Nvidia-driver version. Have you been able to run other pytorch code on cuda on the same machine?

**Comment by iTruffle** [comment]
I tried others pytorch code on the same environment , and failed. 
So i changed another environment to run your code, and got en error like this 
![image](https://user-images.githubusercontent.com/80766557/165284137-a6b1c6da-4f18-410d-b530-a107bd9aaad2.png)
File "tools/demo_track.py", line 77, in inference
    img, ratio = preproc(img, self.test_size, self.rgb_means, self.std)
TypeError: preproc() takes from 2 to 3 positional arguments but 4 were given
What should i do?

**Comment by iTruffle** [comment]
Now i can successfully run the the tracker on a provided demo video from Youtube: python3 tools/demo_track.py --demo_type video -f exps/example/mot/yolox_dancetrack_test.py -c pretrained/bytetrack_dance_model.pth.tar --path videos/dance_demo.mp4 --fp16 --fuse --save_result --out_path demo_out.mp4
But i failed to run the evaluation code with mot17 or mot20.
I got an error like this:
OSError: [Errno 28] No space left on device
![image](https://user-images.githubusercontent.com/80766557/165298245-a1c00987-2dd3-4a7c-8d11-c3b54b30a615.png)
I want to know that how big about the device should i use.

**Comment by noahcao** [comment]
You have no disk space. You do not need much, 50MB might be just enough if you don't save any visualization.
