### ISSUE TITLE
Docker build failed...

### ISSUE THREAD

**Issue by Seoung-wook** [noahcao/OC_SORT#18]
when I tried [2. Docker build]
docker build -t ocsort:latest .
The following problem occurred.

Processing triggers for sgml-base (1.29.1) ...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Removing intermediate container 67ee1859253d
 ---> 686356aae519
Step 6/11 : RUN git clone https://github.com/noahcao/OC_SORT    && cd OC_SORT     && git checkout 3434c5e8bc6a5ae8ad530528ba8d9a431967f237     && mkdir -p YOLOX_outputs/yolox_x_mix_det/track_vis     && sed -i 's/torch>=1.7/torch==1.9.1+cu111/g' requirements.txt     && sed -i 's/torchvision==0.10.0/torchvision==0.10.1+cu111/g' requirements.txt     && sed -i "s/'cuda'/0/g" tools/demo_track.py     && pip3 install pip --upgrade     && pip3 install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html     && python3 setup.py develop     && pip3 install cython     && pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'     && pip3 install cython_bbox gdown     && ldconfig     && pip cache purge
 ---> Running in 66120b5d54d0

Cloning into 'OC_SORT'...
fatal: reference is not a tree: 3434c5e8bc6a5ae8ad530528ba8d9a431967f237

The command '/bin/sh -c git clone https://github.com/noahcao/OC_SORT    && cd OC_SORT     && git checkout 3434c5e8bc6a5ae8ad530528ba8d9a431967f237     && mkdir -p YOLOX_outputs/yolox_x_mix_det/track_vis     && sed -i 's/torch>=1.7/torch==1.9.1+cu111/g' requirements.txt     && sed -i 's/torchvision==0.10.0/torchvision==0.10.1+cu111/g' requirements.txt     && sed -i "s/'cuda'/0/g" tools/demo_track.py     && pip3 install pip --upgrade     && pip3 install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html     && python3 setup.py develop     && pip3 install cython     && pip3 install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'     && pip3 install cython_bbox gdown     && ldconfig     && pip cache purge' returned a non-zero code: 128

If you have encountered a similar problem or know a solution, please comment.

**Comment by noahcao** [comment]
Because so many commands are nested in the step 6. Could you try to split them into single lines? That would be helpful to see which command caused the failure.

**Comment by Seoung-wook** [comment]
Thanks for your reply. I tried line by line in docker file 
RUN git clone https://github.com/noahcao/OC_SORT\
    && cd OC_SORT \
, but I got the same error. It seems to be an error that the tree structure is broken in the part that works well in ByteTrack's build file, but it's a bit difficult.

**Comment by noahcao** [comment]
Oh, yes. I found an error  in the previous Dockerfile. I just made a commit to fix that. Could you try the new version? Sorry for the inconvenience.

**Comment by Seoung-wook** [comment]
omg thank u ^^
I was trying docker file with editing RUN git ByteTrack without  yours^^


Thanks for saving the effort. thanks.
