### ISSUE TITLE
MOT17 demo

### ISSUE THREAD

**Issue by chenrxi** [noahcao/OC_SORT#2]
could you provide tracking demo of MOT17 videos? If possible, could you provide the private detections. Thank you.

**Comment by noahcao** [comment]
Hi, the video for mot17-test is available on the [mot challenge website](https://motchallenge.net/method/MOT=5230&chl=10). For detector, I use the YOLOX detector weights "bytetrack_x_mot17.pth.tar" trained by DanceTrack, you could access that in [their github repo](https://github.com/ifzhang/ByteTrack).

**Comment by noahcao** [comment]
I'm closing the issue. Feel free to follow up for any further issues.
