### ISSUE TITLE
Evaluation DanceTrack

### ISSUE THREAD

**Issue by iTruffle** [noahcao/OC_SORT#20]
Hello,
I ran the evaluation code "python tools/run_ocsort_dance.py -f exps/example/mot/yolox_dancetrack_val.py -c pretrained/bytetrack_dance_model.pth.tar -b 1 -d 1 --fp16 --fuse --expn /output", and got the dancetrack0004.txt like this:
![image](https://user-images.githubusercontent.com/80766557/165510158-161f72e9-9e58-4055-8ee4-9f752e070937.png)
"1,3.0,772.2,309.5,261.9,767.8,-1,-1,-1,-1
1,2.0,969.3,414.5,299.7,579.2,-1,-1,-1,-1"
what are the means of these numbers, and how can i use them?

**Comment by LamnouarMohamed** [comment]
<frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, -1, -1, -1

**Comment by LamnouarMohamed** [comment]
frame, id, bb_left, bb_top, bb_width, bb_height, conf, -1, -1, -1

**Comment by iTruffle** [comment]
What are the means of conf and -1,-1,-1,-1

**Comment by iTruffle** [comment]
What are the means of conf and -1,-1,-1,-1

**Comment by iTruffle** [comment]
![image](https://user-images.githubusercontent.com/80766557/165531787-6b44127f-44b1-47b0-be50-6e69fa1c0307.png)
I ran the evaluation code "python tools/run_ocsort_dance.py -f exps/example/mot/yolox_dancetrack_val.py -c pretrained/bytetrack_dance_model.pth.tar -b 1 -d 1 --fp16 --fuse --expn /output", and got an error like this. What is the "_C" of yolox?

**Comment by noahcao** [comment]
@iTruffle _C is the module for interaction between C lib and python interfaces. Looks like you didn't install the dependency properly.

**Comment by iTruffle** [comment]
Thank you for your responding. I have another question.
![image](https://user-images.githubusercontent.com/80766557/165692154-861b2985-67db-4eb2-b64f-ba03cf2a9a3b.png)
I finished the evaluation code of DanceTrack Val set and DanceTrack Test set. How can i get the datas in this form?  Or where i can find the datas?
![image](https://user-images.githubusercontent.com/80766557/165692227-fd41cfe8-16a2-4ed6-8919-b37170fe1712.png)

**Comment by iTruffle** [comment]
Did not i save the datas?
![image](https://user-images.githubusercontent.com/80766557/165692544-7ae836d8-55ba-41b7-97bd-b45c612fcfa4.png)

**Comment by noahcao** [comment]
Follow [TrackEval](https://github.com/JonathonLuiten/TrackEval) for evaluation. It supports the raw data format of MOT17/DanceTrack, you don't have to do data convert, just setup the data path.

**Comment by noahcao** [comment]
@iTruffle Regarding the output line10-line24, I believe the result files are saved.

**Comment by iTruffle** [comment]
Thank you very much.

**Comment by MargeryLab** [comment]
i can't find "bytetrack_dance_model.pth.tar".

**Comment by iTruffle** [comment]
https://musetransfer.com/s/jcivrsxmu（有效期至5月13日）｜【Muse】你有一份文件待查收，请点击链接获取文件
I forget the download link, but i have the file in my desktop. So i upload into this link, you can get it.

**Comment by MargeryLab** [comment]
> [https://musetransfer.com/s/jcivrsxmu（有效期至5月13日）｜【Muse】你有一份文件待查收，请点击链接获取文件](https://musetransfer.com/s/jcivrsxmu%EF%BC%88%E6%9C%89%E6%95%88%E6%9C%9F%E8%87%B35%E6%9C%8813%E6%97%A5%EF%BC%89%EF%BD%9C%E3%80%90Muse%E3%80%91%E4%BD%A0%E6%9C%89%E4%B8%80%E4%BB%BD%E6%96%87%E4%BB%B6%E5%BE%85%E6%9F%A5%E6%94%B6%EF%BC%8C%E8%AF%B7%E7%82%B9%E5%87%BB%E9%93%BE%E6%8E%A5%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6) I forget the download link, but i have the file in my desktop. So i upload into this link, you can get it.

thank you, but there are some errors when i run the demo video,
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOX:
        Missing key(s) in state_dict: "backbone.backbone.dark2.0.conv.weight", "backbone.backbone.dark2.0.bn.weight", "backbone.backbone.dark2.0.bn.bias", "backbone.backbone.dark2.0.bn.running_mean", "backbone.backbone.dark2.0.bn.running_var", "backbone.backbone.dark2.1.m.0.conv2.conv.weight", "backbone.backbone.dark2.1.m.0.conv2.bn.weight", "backbone.backbone.dark2.1.m.0.conv2.bn.bias", "backbone.backbone.dark2.1.m.0.conv2.bn.running_mean", "backbone.backbone.dark2.1.m.0.conv2.bn.running_var", "backbone.backbone.dark2.1.m.1.conv1.conv.weight", "backbone.backbone.dark2.1.m.1.conv1.bn.weight", "backbone.backbone.dark2.1.m.1.conv1.bn.bias",

**Comment by iTruffle** [comment]
Check your cuda version, cuda10 is enough. I did not have this error.
