### ISSUE TITLE
Why multiply scores?

### ISSUE THREAD

**Issue by majx1997** [noahcao/OC_SORT#23]
作者您好，很感谢您开源这么优异的跟踪器。在阅读您的代码时，我注意到您在处理angle_diff_cost时，将其与scores相乘。这个操作我不太理解，如果您方便的话，请您给讲解一下~
另外，您在处理IoU距离时，将其resize到[0,1]。diff_angle值域是[-0.5,0.5]，由于乘系数vdc_weight 0.2，所以值域变为[-0.1, 0.1]。那么，最终两个框之间的距离在区间[-0.1, 1.1]，请问我这样理解对吗？期待您的回复，感谢！
![image](https://user-images.githubusercontent.com/38154161/165909130-611db159-a2f2-41fb-93de-b798fa0302b9.png)

**Comment by noahcao** [comment]
A reference is like the use of `weight_iou_with_det_scores` in mmtracking [here](https://github.com/open-mmlab/mmtracking/blob/059dc9988791d3afdc65b8c291ae17ee9631b723/mmtrack/models/trackers/byte_tracker.py#L40). You can also find similar practice in many other implementations.

**Comment by majx1997** [comment]
非常感谢您的指点！另外我注意到您的比较里面存在 KITTI-cars 这个数据集，这个是您单独挑出来car这一类别进行测试的吗？如果可以的话，您是否方便分享一下这个数据集？

**Comment by noahcao** [comment]
@majx1997 Please use English or English+Chinese for issue comments, which would benefit a broad community.

You question: you noticed I make an entry of "KITTI-cars" in the table. Did I select cars instances from the evalution?

Answer: No. I directly run the experiments on the standard KITTI benchmark. The evaluation server would do category-wise evaluation. Please check its [website](http://www.cvlibs.net/datasets/kitti/eval_tracking.php) for details.
