### ISSUE TITLE
Use OC-SORT to track cells

### ISSUE THREAD

**Issue by owen24819** [noahcao/OC_SORT#24]
Hi, really nice work here. Excited to potentially test this software out. I apologize for posting this as an issue but I wanted to get your opinion.

I am currently looking for a tracking algorithm to track bacterial cells. I know I will have to figure out the cell divisions but do you think OC-SORT could track bacterial cells? I provded a movie below as an example. The DanceTrack dataset is the closest thing I've found that is relevent to cells growing (uniform appearance and nonlinear motion) and OC-SORT was able to get SOTA results. 

I've read through a fair amount of your code but it will still take a fair amount of work for me to adapt this to tracking cells (as I am currently learning about the kalman filter) so I just wanted to get your opinion before I spend more time on it. 

Edit: I have a model that can segment the cells so I will not need YOLO to detect the cells. I am primarily interested in just tracking the cells.

Thanks in advance.

https://user-images.githubusercontent.com/55507279/166089470-59a4652e-3dac-41c1-862c-f3a6513638a7.mp4

**Comment by noahcao** [comment]
I have no experience on this project. But this is an interesting case that two objects will emerge from one target. By watching the provided video, I think IoU is a reliable cue to track the objects as you want. Regarding this, I think all IoU-based tracker, of course including OC-SORT, should be worth giving a try.

**Comment by owen24819** [comment]
Awesome. I appreicate the insight.
