### ISSUE TITLE
demo video is not works

### ISSUE THREAD

**Issue by MargeryLab** [noahcao/OC_SORT#26]
when i run the demo given in README, i can not find the pretrained model "bytetrack_dance_model.pth.tar", and i used "ocsort_dancetrack.pth.tar" given in model zoo, python tools/demo_track.py --demo_type video -f exps/example/mot/yolox_dancetrack_test.py -c pretrained/bytetrack_dance_model.pth.tar --path videos/dance_demo.mp4 --fp16 --fuse --save_result --out_path demo_out.mp4,  but the result has no any bounding boxes?

**Comment by MargeryLab** [comment]
> Hi @MargeryLab That was a naming issue, please use the checkpoint `ocsort_dance_model.pth.tar` you find. So the command should be
> 
> ```
> python tools/demo_track.py --demo_type video -f exps/example/mot/yolox_dancetrack_test.py -c pretrained/ocsort_dance_model.pth.tar --path videos/dance_demo.mp4 --fp16 --fuse --save_result --out_path demo_out.mp4
> ```
> 
> I have updated the readme instruction. Thank you.

thank you for your reply, but why has no bounding boxes predicted?

**Comment by noahcao** [comment]
Have you modified any code? I tried to re-install, download the weights and run the command above. It works smoothly on my side with expected output trajectories. 

Can you confirm if you have the checkpoint loaded during making the demo?

**Comment by MargeryLab** [comment]
> 

i didn't modify any code, torch version is 1.7.1 and cuda11.0, logs as follows:
![image](https://user-images.githubusercontent.com/57980908/167233770-35934554-9a19-4591-a529-a143cea9a7db.png)

**Comment by noahcao** [comment]
Could you give an access of your output video? The logs you show looks as expected to me.

**Comment by MargeryLab** [comment]
> Could you give an access of your output video? The logs you show looks as expected to me.

I have solved it, I removed "--fp16" and got the correct result, I found that fp16 makes one conv layer output nan and cause subsequent output to be all nan, maybe it is a environment problem, but I tried torch1.7 , 1.8, 1.10 are the same output.

**Comment by noahcao** [comment]
This is interesting. Considering fp16 is related to mixed accuracy weights, I would also suspect this is related to the hardware.
