### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox'

### ISSUE THREAD

**Issue by iTruffle** [noahcao/OC_SORT#29]
I successfully ran the code last week. But i failed today. 
I strcutly follow the readme, and installed libglib2.0-dev. 
I want to test the video you provided. 

> python3 tools/demo_track.py --demo_type video -f exps/example/mot/yolox_dancetrack_test.py -c pretrained/bytetrack_dance_model.pth.tar --path videos/dance_demo.mp4 --fp16 --fuse --save_result --out_path demo_out.mp4

And i got an error like this: 
![image](https://user-images.githubusercontent.com/80766557/167615905-88865f98-3aad-4965-8feb-96240ab25edf.png)
I also got this error last week, and change the path to solve it, and then i got other errors. 
I do not want to modify this code. 
Why is it happen? 
What should i do to sovle it?
![image](https://user-images.githubusercontent.com/80766557/167617790-5ae840fe-41d0-41bd-9ca5-9b4efbf85878.png)

**Comment by iTruffle** [comment]
I do not upload the pretrained files, but it is not the reason of this error.

**Comment by noahcao** [comment]
Hi @iTruffle ,

Unfortunately, I can not reproduce this issue. I recommend you to re-install the required dependency as explained in INSTALL.md.

**Comment by iTruffle** [comment]
Ok. And, what is the 'docker build' in INSTALL.MD? Should i build it? 
![image](https://user-images.githubusercontent.com/80766557/168198326-e9aa0c63-e414-4e77-a5c6-d1b890198a12.png)
I have not build the docker.

**Comment by noahcao** [comment]
Only if you'd like to run the program in a docker environment, you should build the image. Otherwise, you don't have to build it.

**Comment by noahcao** [comment]
As this issue relates to the content already explained in the INTSALL.md document, I'm closing it now.
