### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by shituo123456** [noahcao/OC_SORT#3]
fps

**Comment by noahcao** [comment]
With YOLOX as ByteTrack uses, the FPS on MOT17 and DanceTrack is around 32FPS on RTX 2080 Ti + i9 @ 3GHz. If given off-shelf detection results, the FPS on KITTI is around 700 FPS by i9 @ 3GHz.

**Comment by JLJ19** [comment]
Is the fps calculation for off-shelf detections using 1 core?
