### ISSUE TITLE
[Question] Where is the code of OOS？

### ISSUE THREAD

**Issue by CaptainEven** [noahcao/OC_SORT#30]
I 'm confused about finding OOS code for virtual trajectory generation, can you offer some help?

**Comment by noahcao** [comment]
I did OOS by the customized Kalman Filter in `trackers/ocsort_tracker/kalmanfilter.py`.

**Comment by CaptainEven** [comment]
> I did OOS by the customized Kalman Filter in `trackers/ocsort_tracker/kalmanfilter.py`.

Could you please point out the point more sepecificlly?

**Comment by HanGuangXin** [comment]
@CaptainEven What the author said in another issue: "the OOS is realized by the freeze/unfreeze of parameters in my customized [Kalman Filter](https://github.com/noahcao/OC_SORT/blob/b43384f28fbe78910064efbc9189a569128a1b89/trackers/ocsort_tracker/kalmanfilter.py#L109)."

**Comment by CaptainEven** [comment]
@noahcao @HanGuangXin Thansk for the answer!

**Comment by Stephen-Ning** [comment]
> @CaptainEven作者在另一期说的：“OOS是通过我定制的[Kalman Filter](https://github.com/noahcao/OC_SORT/blob/b43384f28fbe78910064efbc9189a569128a1b89/trackers/ocsort_tracker/kalmanfilter.py#L109)中参数的freeze/unfreeze实现的。”

Where is the OCM code？Can you help me?
