### ISSUE TITLE
Problem with interpolation.py

### ISSUE THREAD

**Issue by ajwl27** [noahcao/OC_SORT#31]
Hi,

I've been trying to use `dti()` in interpolation.py with the results I get from demo_track.py, but I think this function has a problem - on line 78 of interpolation.py, I  believe ` n_frame = tracklet.shape[0]` will always return 1. Therefore I don't think the following code is ever run. And when I have tried to change this, e.g. `n_frame = int(tracklet[:,0])` , I run into different problems, e.g. I think the score threshold doesn't work because in demo_track.py the score is always written as 1.0 - 
 `results.append(f"{frame_id},{tid},{tlwh[0]:.2f},{tlwh[1]:.2f},{tlwh[2]:.2f},{tlwh[3]:.2f},1.0,-1,-1,-1\n"))`  .

If you could tell me how to usethis code with the text files output by demo_track I would be very grateful.

Thanks

**Comment by noahcao** [comment]
Hi @ajwl27 

Why do you think the return of `n_frame = tracklet.shape[0]` should be always 1? In fact, it should not be if only the length of trackless is not 1. I tested the code and it ran smoothly. Could you provide the tracking output .txt files here to help debug?

**Comment by ajwl27** [comment]
Thanks for the reply @noahcao 

I uploaded the first 500 trackfiles output from demo_track from my source video - https://drive.google.com/file/d/18_w2SdpJojjlPxEsqI3H6IJFiK6prZV5/view?usp=sharing

Sorry if I misunderstand, but I think ` tracklet.shape[0]` will be 1 because tracklet is a list with data from a single line (track) from a single track file (ie. all outputs from 1 frame). Something like `[1,801.0,1970.00,1948.00,68.00,52.00,1.0,-1,-1,-1]`

**Comment by noahcao** [comment]
I feel confused about the uploaded files. In default, given one video, the output file should be just one .txt file instead of 500.

tracklet should a array of size T x 10, where T is the time length of the tracklet. 

You may want to refer to the [data format of motchallenge](https://motchallenge.net/instructions/) for reference, on which the `interpolation.py` is supposed to work.

**Comment by ajwl27** [comment]
Sorry for the delay replying to you. I think this is my fault, I think I was using some code from BYTETrack's demo file instead of the OC-SORT one. I've rerun the tracking to get a single trackfile and it seems to be working now. Thanks for your prompt help :)
