### ISSUE TITLE
[Multi-class multi-object] implementtion branch release

### ISSUE THREAD

**Issue by CaptainEven** [noahcao/OC_SORT#33]
https://github.com/CaptainEven/MCMOT-ByteTrack

**Comment by CaptainEven** [comment]
choose byte or oc_sort as the MCMOT tracker's backend.

**Comment by CaptainEven** [comment]
thanks for reminding!

**Comment by gachiemchiep** [comment]
> Looks good! Also note OC-SORT can support multi-class multi-object tracking by forcing objects of different categories never matched as [here](https://github.com/noahcao/OC_SORT/blob/bfa9aa6af44570b9049aae8fcad57773e010886a/trackers/ocsort_tracker/ocsort.py#L381).
> 
> Moreover, I made two PRs to mmtracking to support [OC-SORT](https://github.com/open-mmlab/mmtracking/pull/545) and [MCMT (using ByteTrack as an example)](https://github.com/open-mmlab/mmtracking/pull/548) if you want to work with a more customized codebase.

Hello. 
Thank you for your great work.

Did your PR on mmtracking support the Multi-class multi-object?
