### ISSUE TITLE
[question] why use velocity direction(the unit vector) rather than velocity vector(including uint vector and norm) to match?

### ISSUE THREAD

**Issue by CaptainEven** [noahcao/OC_SORT#34]

**Comment by Stephen-Ning** [comment]
![1677228090817](https://user-images.githubusercontent.com/108001646/221133489-cbb99eb5-4491-4382-b12d-12d19fffefa9.jpg)
Hello! Excuse me, where is the code of OCM? Can you help me?

**Comment by Stephen-Ning** [comment]
> @noahcao感谢您的解释！

Look forward to your reply！
