### ISSUE TITLE
AssertionError: plz provide exp file or exp name.

### ISSUE THREAD

**Issue by Seoung-wook** [noahcao/OC_SORT#35]
When I tried python3 tools/demo_track.py video -f exps/example/mot/yolox_s_mix_det.py --trt --save_result,
The error is occured.

Traceback (most recent call last):
  File "tools/demo_track.py", line 280, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "/workspace/OC_SORT/yolox/exp/build.py", line 47, in get_exp
    assert (
AssertionError: plz provide exp file or exp name.

Forcibly entering exp name did not solve the problem.
ex)args.exp_file ='~~~~.pth'

If anyone knows a solution, please share.

**Comment by Seoung-wook** [comment]
in docker container, byteTrack is inferences well..... what happend?

**Comment by gyh420** [comment]
any result？
