### ISSUE TITLE
TrackEval for mot_challenge

### ISSUE THREAD

**Issue by iTruffle** [noahcao/OC_SORT#37]
Hello, thank you very much for your excellent work. I got [TrackEval ](https://github.com/JonathonLuiten/TrackEval)to evaluate mot_challenge. But TrackEval just have python files and samples for train sets, do not have files or samples for test sets. Would i get your python project for evaluating mot_challenge?

**Comment by noahcao** [comment]
I have no annotations for test set. You should submit your results to their [evaluation server](https://motchallenge.net/) for that.

**Comment by iTruffle** [comment]
Do you mean this "login to submit"? 
![image](https://user-images.githubusercontent.com/80766557/170922522-83d91df3-f572-472b-9a5a-6fe2b1f90fd2.png)

**Comment by noahcao** [comment]
Yes.

**Comment by iTruffle** [comment]
Thank you very much.
