### ISSUE TITLE
How about C++ version ?

### ISSUE THREAD

**Issue by uyolo1314** [noahcao/OC_SORT#38]

**Comment by noahcao** [comment]
at this moment, i don't have the bandwidth to write a full C++ version. If you'd like to deploy on some mobile device, a workaround is to use the DEPLOYMENT i provided in the Readme. Or, it would be extermely welcome if you can make a contribution of an independent implementation.

**Comment by CaptainEven** [comment]
I will do the C++ implementation.

**Comment by xinsuinizhuan** [comment]
> I will do the C++ implementation.
 very much expect。I find the deploy, but it is bytetrack implementation。I hope the OC_SORT the C++ implementation

**Comment by LiquorPerfect** [comment]
> I will do the C++ implementation.

您好，你那边实现了吗，我没有找到哎。

**Comment by paleomoon** [comment]
Hi, any update? the C++ implementation of this repo is bytetrack.
