### ISSUE TITLE
TypeError: compare_to_groundtruth() got an unexpected keyword argument 'vflag'

### ISSUE THREAD

**Issue by Richard1121** [noahcao/OC_SORT#44]
@noahcao Hi!
when  I run :
python3 tools/run_ocsort.py -f exps/example/mot/yolox_x_ablation.py -c pretrained/bytetrack_ablation.pth.tar -b 1 -d 1 --fp16 --fuse --expn MOT17

the error is :

File "tools/run_ocsort.py", line 32, in compare_dataframes
    accs.append(mmp.utils.compare_to_groundtruth(gts[k], tsacc, 'iou', distth=0.5,vflag = vflag))
TypeError: compare_to_groundtruth() got an unexpected keyword argument 'vflag'

**Comment by noahcao** [comment]
Hi @Richard1121,

Have you fixed this issue? this looks like an issue from motmetric version. In my provided version, the parameters into this function should be aligned (see [motmetrics/utils.py](https://github.com/noahcao/OC_SORT/blob/bfa9aa6af44570b9049aae8fcad57773e010886a/motmetrics/utils.py#L21)).

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！

**Comment by YamacTan** [comment]
I am facing the same issue and I have downgraded Motmetrics version by 2 relase. There was no change. Could it be caused by another problem? The function seems to be defined correctly.

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！

**Comment by Decarryee** [comment]
I am facing the same issue. Could you tell me how to fix it?

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！

**Comment by Misaka10088** [comment]
pip uninstall motmetrics

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！

**Comment by levi5611** [comment]
> @noahcao Hi! when I run : python3 tools/run_ocsort.py -f exps/example/mot/yolox_x_ablation.py -c pretrained/bytetrack_ablation.pth.tar -b 1 -d 1 --fp16 --fuse --expn MOT17
> 
> the error is :
> 
> File "tools/run_ocsort.py", line 32, in compare_dataframes accs.append(mmp.utils.compare_to_groundtruth(gts[k], tsacc, 'iou', distth=0.5,vflag = vflag)) TypeError: compare_to_groundtruth() got an unexpected keyword argument 'vflag'

请问你的问题解决了吗？我也遇到了同样的问题

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！

**Comment by levi5611** [comment]
> I am facing the same issue. Could you tell me how to fix it?
 am facing the same issue. Do you fix it?

**Comment by Elite35P** [comment]
I am facing the same issue. Could you tell me how to fix it?
am facing the same issue. Do you fix it?

**Comment by Richard1121** [comment]
你发的邮件已收到...谢谢！
