### ISSUE TITLE
OC_Sort Vs. ByteTracker Inference Speed

### ISSUE THREAD

**Issue by Rm1n90** [noahcao/OC_SORT#46]
Hello @noahcao, 

Thanks for sharing the code. I have a question regard to speed of OC_Sort. 
Im using YoloV5 as a object detector for both OC_Sort and ByteTracker tracking algorithm with the same setting. However, all the process for one frame (Detection and tracking) took almost ~14ms for ByteTracker and  ~45ms for OC_Sort. I would like to ask you how can I speed up the OC_Sort (Based on your paper, OC_Sort should be faster than ByteTrack)?

Thanks!

**Comment by noahcao** [comment]
Hi @Rm1n90,

Yes, in my raw implementation, OC-SORT should be slightly faster than ByteTrack. In this repo, the released version is based on a naive and less efficienct implementation. The key should be in the FOR-loops in [oc-sort](https://github.com/noahcao/OC_SORT/blob/master/trackers/ocsort_tracker/ocsort.py). I am not updating this repo in the coming days as my focus is to support a higher-efficient version in mmtracking (see [PR in mmtracking](https://github.com/open-mmlab/mmtracking/pull/545)), for which we would make it faster.

Apologize for the confusion and inconvenience I make here.

**Comment by mohaghighat** [comment]
Does this repo has the efficient code yet, or should we only use the version in the mmtracking?

**Comment by noahcao** [comment]
@mohaghighat 

For the time efficiency, they are almost the same. This version is cleaner if you only want to use OC-SORT. The mmtracking version is more flexible if you'd like to try more features, such as adaptive detector, backbones, more engineering tricks etc.
