### ISSUE TITLE
run OC-SORT on KITTI dataset

### ISSUE THREAD

**Issue by cuonga1cvp** [noahcao/OC_SORT#48]
Dear author,
I had some problem when I ran OC-SORT on KITTI dataset. Maybe my steps were wrong. Could you please guide me how to run OC_SORT on KITTI dataset?
Thank you so much.
BRs,
cuonga1cvp.

**Comment by noahcao** [comment]
Hi @cuonga1cvp ,

To test on KITTI, my purpose was to evaluate the generalisability of OC-SORT. Thus, I didn't try a detector on KITTI, I run OC-SORT over the detection results from [PermaTrack](https://github.com/TRI-ML/permatrack). Please see instructions in [GET_STARTED](https://github.com/noahcao/OC_SORT/blob/master/docs/GET_STARTED.md) for details. Once you have PermaTrack's result, you should be able to get results from OC-SORT very quickly as no training is needed.

**Comment by noahcao** [comment]
@cuonga1cvp 
Hope you have fixed your issue. I'm closing this issue. Please feel free to reopen it if you have any other related problems.
