### ISSUE TITLE
cannot import name 'MOTDataset'

### ISSUE THREAD

**Issue by echo-sky** [noahcao/OC_SORT#5]
When I run test on MOT17, the error occurs below.

cannot import name 'MOTDataset'

And I search in the whole project, and I have not found the definition of "MOTDataset".

How can I solve it.

Many thanks.

**Comment by echo-sky** [comment]
![Screenshot from 2022-04-05 15-22-11](https://user-images.githubusercontent.com/46777015/161701921-6cf190e8-41e9-4bd4-a516-9d670ee7debe.png)

Which is shown above. Need help~~~~~~~~~~~~~~    Thanks.

**Comment by noahcao** [comment]
Sorry for my fault. This is caused a missing uploaded directory *yolox/data/datasets* because of a typo in .gitignore file. I have uploaded the directory. Please let me know if there is still issue on your side.
