### ISSUE TITLE
exps/permatrack_kitti_test

### ISSUE THREAD

**Issue by cuonga1cvp** [noahcao/OC_SORT#51]
Dear author,
I saw the data in exps/permatrack_kitti_test contains frame_ids, object_ids, object positions, results of detection and the object_ids are already connected between frames. 
Can you explain why there are object_ids here? Because I think the output of Permatrack-detector just contains object positions and accuracy of the detection and there no object_ids,
BRs,
cuonga1cvp

**Comment by noahcao** [comment]
Hi I simply run the tracking code of PermaTrack, which outputs object_ids as well. During running OC-SORT over the results, there objects_id will NOT be used. We regard them as just detection during the use.

**Comment by cuonga1cvp** [comment]
oh I see. 
Thanks a lot
