### ISSUE TITLE
[Question] Any pretrained weight avaliable for car tracking?

### ISSUE THREAD

**Issue by YamacTan** [noahcao/OC_SORT#53]
Hi Jinkun and thanks for the great work again!

I've seen OC_SORT get a very good MOTA score on KITTI-cars dataset. I would like to verify such a score with the demo road camera videos I have, but I think the pretrained weights presented on this repository and Bytetrack are only prepared for "Human".

Is there any pretrained car tracking weight for OC_SORT? Or do I need to perform training on a suitable dataset first?

Bests,
Y.

**Comment by noahcao** [comment]
I don't provide that. For the experiments on KITTI, I directly use the detections from another method, i.e. Permatrack.

But it should be feasible by boughting car detector from other models?
