### ISSUE TITLE
Customized Detector -- Example

### ISSUE THREAD

**Issue by jpoberhauser** [noahcao/OC_SORT#54]
Hi, I added a Predictor class to work with any `yolov5` detector. I saw on the Roadmap that adding customizable Predictor objects is helpful, so I am leaving it here in case its useful for other people or in case you want me to submit a PR. 

There are a couple things I couldn't figure out yet like the purpose of `img_info["ratio"]` and I left the preprocessing function commented out for now. Hope it's helpful for other people. 

```
import yolov5
class PredictorV5(object):
    def __init__(self, model_path, conf, iou):
        self.model_path = model_path
        self.model = yolov5.load(self.model_path)
        self.conf = conf
        self.iou = iou

    def inference(self, img, timer):
        img_info = {"id": 0}
        if isinstance(img, str):
            img_info["file_name"] = osp.basename(img)
            img = cv2.imread(img)
        else:
            img_info["file_name"] = None
        
        height, width = img.shape[:2]
        img_info["height"] = height
        img_info["width"] = width
        img_info["raw_img"] = img
        img_info["ratio"] = .999999
        #img, ratio = preprocess_v5(img, self.test_size, self.rgb_means, self.std)
        self.model.conf = self.conf
        results = self.model(img)
        timer.tic()
        predictions = results.pred[0]
        if len(predictions)==0:
            return [None], img_info
        else:
            boxes = predictions[:, :4].tolist()
            boxes_int = torch.tensor([[int(v) for v in box] for box in boxes])
            scores = torch.tensor(predictions[:,4].tolist())
            outputs = [torch.cat((boxes_int, torch.unsqueeze(scores, dim=1)), 1)]
            return outputs, img_info
```

**Comment by JokaKanlic** [comment]
Hi, can you tell me where this Predictor class is added? I want to use OC-SORT with yolov7, would this class be useful with that detector?

**Comment by jpoberhauser** [comment]
You would add this as your `Predictor` class in `tools/demo_track.py`. 

For yolov7, you might have to change a couple of things around, but if you take a look at their inference script you can basically just rip out the inference code and stick into the `Predictor` class.

**Comment by noahcao** [comment]
Thanks so much @jpoberhauser for the awesome contribution.

Now, we could also use OC-SORT with customized detector by the implementation of [mmtracking](https://github.com/noahcao/mmtracking.git).
