### ISSUE TITLE
Pre-trained wieghts

### ISSUE THREAD

**Issue by jerichosu** [noahcao/OC_SORT#55]
Just want to confirm:

**MOT17-half-val** --> **ocsort_mot17_ablation.pth.tar**, same as **bytetrack_ablation.pth.tar** (based on ByteTrack: Train on CrowdHuman and MOT17 half train, evaluate on MOT17 half val)

**MOT17-test** --> **ocsort_x_mot17.pth.tar**, same as **bytetrack_x_mot17.pth.tar** (based on ByteTrack: Train on CrowdHuman, MOT17, Cityperson and ETHZ, evaluate on MOT17 train. -->  **Yes they said they are evaluating on MOT17 train, but I guess that is a typo? I'm not sure here MOT17 train or MOT17 train half is used for training**)

**MOT20-test** --> **ocsort_x_mot20.pth.tar**, same as **bytetrack_x_mot20.pth.tar** (based on ByteTrack: Train on CrowdHuman and MOT20, evaluate on MOT20 train. **I guess this is a typo as well, not sure if it is trained using MOT20 train of train half?**)

**Comment by noahcao** [comment]
Yes, Bytetrack and OC-SORT use the same detector weights for fair comparison.
