### ISSUE TITLE
Use generated detections from custom detector in form of .txt file

### ISSUE THREAD

**Issue by JovanBosic** [noahcao/OC_SORT#56]
Hi, first of all thank you for this repo. I am doing an project where I am using 7 different object detectors and I would like to use their detectons and put them in txt file which I would like to use with your tracking algorithm so I can compare them all. I know that this is possible but can you help me a little more with this?

Kind regards,
Jovan

**Comment by noahcao** [comment]
Yes, this is possible and has been implemented to do tracking on KITTI, where we use the detection from existing models and put them in .txt files.

You may want to refer to how we run on KITTI [here](https://github.com/noahcao/OC_SORT/blob/master/docs/GET_STARTED.md). In the implementation of OC-SORT, there is an interface for tracking over given detections as [update_public](https://github.com/noahcao/OC_SORT/blob/589019f2237b54a017fdc978ff1a78ac4d4e8d49/trackers/ocsort_tracker/ocsort.py#L327).
