### ISSUE TITLE
I got "CUDA out of memory", should i reduce training data? or there is another way? 

### ISSUE THREAD

**Issue by ganhao88688** [noahcao/OC_SORT#58]
command:
`py -3.8 tools/train.py -f exps/example/mot/yolox_x_ablation.py -d 1 -b 3 --fp16 -o -c pretrained/yolox_x.pth`
Error:
![image](https://user-images.githubusercontent.com/48307398/189086222-75a54577-99c9-44d1-a2b1-c157e3514c3a.png)
...
`
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.29 GiB already allocated; 0 bytes free; 5.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
Willl the shape mismatch cause an error?
i also tried batch size=1, but it have to run for 7 days QQ

**Comment by noahcao** [comment]
I don't think the shape mismatch causes the OOM error. You might need a GPU with bigger memory to run with the exactly same model and checkpoint. If you'd like a more memory-economic solution, you can refer to the implementation of OC-SORT in [mmtracking](https://github.com/open-mmlab/mmtracking) to replace with a lightweight detector.
