### ISSUE TITLE
Suggestion for parameter optimization

### ISSUE THREAD

**Issue by YamacTan** [noahcao/OC_SORT#59]
Hi,
 
When using the algorithm with the YOLOX_X trained with the COCO dataset for 80 classes, I cannot get the results I expected.

When I use the videos for detection directly in YOLOX, I can get results with high confidence. But when I run the demo track by changing the number of classes in the experiment file to 80, I get the following results.

**Here is the tracking output of OC_SORT for a random frame.**

![track](https://user-images.githubusercontent.com/63727076/189888585-01e605ff-5f8d-4c37-b855-cb20057fc116.png)

**And this is the related YOLOX_X detector output for that frame.**
![detect](https://user-images.githubusercontent.com/63727076/189888746-323304e3-e353-47e8-8712-b08f2093bbf9.png)

The situation is same when there are only one car at the frame. Likewise, when I try on some other algorithms using YOLOX detector (i.e [Unitrack](https://github.com/Zhongdao/UniTrackl)), I can get satisfactory results. When I run the "palace.mp4" video in the [Bytetrack](https://github.com/ifzhang/ByteTrack) repository on OC_SORT using the same detector, I get a very successful result. There is probably a point I missed.

I also tried making changes to some parameters in `utils/args` but the result is still not what I expected. Do you have any advice on parameter optimization?

Thanks.

**Comment by noahcao** [comment]
Can you justify the IoU between KF estimates and bounding boxes? For the default implementation, ByteTrack and OC-SORT supports the association among objects of the same category only. But this can be extended as [OC-SORT does on KITTI](https://github.com/noahcao/OC_SORT/blob/589019f2237b54a017fdc978ff1a78ac4d4e8d49/trackers/ocsort_tracker/ocsort.py#L355).
