### ISSUE TITLE
cannot import name 'MOTEvaluatorDance'

### ISSUE THREAD

**Issue by pq-hub** [noahcao/OC_SORT#6]
Thank you for your great work.
when I evaluate the dancetrack verification, I get an import package error, what is the reason?
![Uploading Snipaste_2022-04-05_15-58-26.jpg…]()

**Comment by noahcao** [comment]
Sorry, I can't see your uploaded image. But I tried the code and it works on my side. The class MOTEvaluatorDance should be imported by this [line](https://github.com/noahcao/OC_SORT/blob/06a690f235f9f55fe7efd451797c34e52ccaac6c/yolox/evaluators/__init__.py#L7). So is this a issue in importing relative directory on your side?

**Comment by pq-hub** [comment]
感谢您的回复，目前可以train检测器可以demo可视化跟踪效果；但track时存在如下问题，期待您的回答


1. dancetrack数据集在评估跟踪器
python tools/run_ocsort_dance.py -f exps/example/mot/yolox_dancetrack_val.py -c pretrained/ocsort_dancetrack.pth.tar -b 1 -d 1 --fp16 --fuse
mot指标出现为0 null的情况，请问是什么原因





2. 我看了一下加载的dancetrack的val文件夹下面有gt标签











3. 加载的这个mot17数据集是用来评估检测器还是跟踪器?下面的coco指标是dancetrack数据集再yolox检测器上的指标，还是在mot17上的指标？










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "noahcao/OC_SORT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 晚上9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [noahcao/OC_SORT] cannot import name 'MOTEvaluatorDance' (Issue #6)





 
Sorry, I can't see your uploaded image. But I tried the code and it works on my side. The class MOTEvaluatorDance should be imported by this line. So is this a issue in importing relative directory on your side?

**Comment by noahcao** [comment]
Hi, for the convenience of other users, we recommend to discuss in English.

For your question: it outputs null when running the command:
```
python tools/run_ocsort_dance.py -f exps/example/mot/yolox_dancetrack_val.py -c pretrained/ocsort_dancetrack.pth.tar -b 1 -d 1 --fp16 --fuse
```

It is expected. As I mentioned in the [document](https://github.com/noahcao/OC_SORT/blob/master/docs/GET_STARTED.md), we follow the [TrackEval protocol](https://github.com/DanceTrack/DanceTrack/tree/main/TrackEval) for evaluation on DanceTrack val. You should configurate the evaluation code as indicated by [DanceTrack](https://github.com/DanceTrack/DanceTrack) and  [TrackEval](https://github.com/DanceTrack/DanceTrack/tree/main/TrackEval). Our code does not automatically evaluate it on DanceTrack-val after inference.

I will update the redundant code in that file and guidelines in the document. Thanks for proposing that.

**Comment by pq-hub** [comment]
&nbsp; &nbsp; &nbsp;First of all, I apologize to you. Because I was too excited, I forgot to reply in English just now. I will pay attention to it next time.&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;Your suggestion has been received, and I will learn more about trackeval later.&nbsp;&nbsp;Finally, thanks again for the author's reply, looking forward to the update of your project.

&nbsp; &nbsp; &nbsp;I wish you a happy day





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "noahcao/OC_SORT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 中午1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [noahcao/OC_SORT] cannot import name 'MOTEvaluatorDance' (Issue #6)





 
Hi, for the convenience of other users, we recommend to discuss in English.
 
For your question: it outputs null when running the command:
 python tools/run_ocsort_dance.py -f exps/example/mot/yolox_dancetrack_val.py -c pretrained/ocsort_dancetrack.pth.tar -b 1 -d 1 --fp16 --fuse  
It is expected. As I mentioned in the document, we follow the TrackEval protocol for evaluation on DanceTrack val. You should configurate the evaluation code as indicated by DanceTrack and  TrackEval. Our code does not automatically evaluate it on DanceTrack-val after inference.
 
I will update the redundant code in that file and guidelines in the document. Thanks for proposing that.

**Comment by noahcao** [comment]
Thank you for your follow-ups!

I have updated the code. Now you can have the automatic evaluation after inference on dancetrack-val. But this evaluation uses motmetrics lib which does not support the most important HOTA evaluation. So I still suggest to manually evaluate the output with TrackEval after inference.

**Comment by noahcao** [comment]
I'm closing this issue, hoping I have answered your questions and fixed the issues. Feel free to create new issue for other problems or re-open this for this exact issue. Thank you.

**Comment by pq-hub** [comment]
ok🤗



---Original---
From: "Jinkun ***@***.***&gt;
Date: Wed, Apr 6, 2022 14:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [noahcao/OC_SORT] cannot import name 'MOTEvaluatorDance' (Issue #6)




 
I'm closing this issue, hoping I have answered your questions and fixed the issues. Feel free to create new issue for other problems or re-open this for this exact issue. Thank you.

**Comment by pq-hub** [comment]
Ok, I'll give it a try




---Original---
From: "Jinkun ***@***.***&gt;
Date: Wed, Apr 6, 2022 14:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [noahcao/OC_SORT] cannot import name 'MOTEvaluatorDance' (Issue#6)




 
Thank you for your follow-ups!
 
I have updated the code. Now you can have the automatic evaluation after inference on dancetrack-val. But this evaluation uses motmetrics lib which does not support the most important HOTA evaluation. So I still suggest to manually evaluate the output with TrackEval after inference.
