### ISSUE TITLE
Questions About Pretrained Weights

### ISSUE THREAD

**Issue by ZXYFrank** [noahcao/OC_SORT#60]
Hi! Thanks a lot for this neat and splendid work for MOT community.

Here https://github.com/noahcao/OC_SORT/blob/master/docs/MODEL_ZOO.md you provided some YOLOX weights. I opened the Google Drive links and found that there is only one model for DanceTrack. 

I use it for DanceTrack-test and get a HOTA score of 54.9, which is close to 55.1. (I wonder if you have witnessed some noise of test metrics) 

I want to know what data has been used for training **ocsort_dance_model.pth.tar**.  In [MODEL_ZOO](https://github.com/noahcao/OC_SORT/blob/master/docs/MODEL_ZOO.md#model-zoo) there is DanceTrack-val, but **DanceTrack-val** and **DanceTrack-test** share that same model. Does it mean that this model is finetuned only with _**DanceTrack-train**_?

Furthermore, I wonder which model is this DanceTrack YOLOX inherited from [ByteTrack MODEL_ZOO](https://github.com/ifzhang/ByteTrack#model-zoo).

It would be better if you can provide the training strategy for further investigation. 😃

**Comment by noahcao** [comment]
For dancetrack, we only use Dancetrack-train for training. the val set of Dancetrack is never used for training. 

A variance of 0.2HOTA is possible. Sometimes, even running the model on different GPUs can cause such a scale of variance (for example, some GPUs have double-float check, some other don't). 

Bytetrack used to provide the configurations and weights on DanceTrack. But still, you can find the config here: https://github.com/noahcao/OC_SORT/tree/master/exps/example/mot
