### ISSUE TITLE
python tools/run_ocsort.py  suspended at ./yolox/utils/boxes.py(71)

### ISSUE THREAD

**Issue by YaoMufeng** [noahcao/OC_SORT#61]
Thank you for your great work.
I trained yolox on my own data and when testing, I got suspended at:
OC_SORT/yolox/utils/boxes.py(71)postprocess()-> detections = detections[nms_out_index]

here is the output of the programs:
![image](https://user-images.githubusercontent.com/36182583/196344800-2fa0030d-21b4-4380-a4ea-51b565d7c20c.png)

I don't know why the program suspended, could you please help me fix it?

**Comment by noahcao** [comment]
I can't reproduce this issue on the datasets I investigate. I get there should be something wrong related to your customization for the own dataset.
