### ISSUE TITLE
Some problems of occlusion in dataset

### ISSUE THREAD

**Issue by Stephen-Ning** [noahcao/OC_SORT#62]
![1666094692579](https://user-images.githubusercontent.com/108001646/196425746-342b5ce4-fba2-4471-a5cc-ee248ee63eae.jpg)
![1666094730519](https://user-images.githubusercontent.com/108001646/196425754-d56e98fe-e4e9-4480-97f1-85b74b671619.jpg)
![1666094743954](https://user-images.githubusercontent.com/108001646/196425758-9f899406-5c69-47ec-bf81-ddc82e149a5c.jpg)
![1666094760659](https://user-images.githubusercontent.com/108001646/196425762-e6dab82b-1ffd-4a68-b6cc-81cb58673189.jpg)
![1666094775549](https://user-images.githubusercontent.com/108001646/196425764-68d47285-5f3a-44de-a6ba-b64b2a1b992b.jpg)

**Comment by noahcao** [comment]
The issue should lies in the detector. To be precise, the detector gives inaccurate bounding boxes on the second image. When trying to associate the bounding boxes on the first and the second images, the IoU for the bounding box of the right-hand person is small so OC-SORT generates a new tracklet for it (#4). But track#3 is still alive and propagates at the background. When it comes to the later steps, the detected bounding box is more matched to the box estimate from track#3 (they have close aspect ratio, position so probably have a higher IoU), so the track#3 is activated by the new-coming box.

**Comment by Stephen-Ning** [comment]
Thank you for your answer. How should I print the iou of a pair of bounding boxes?
