### ISSUE TITLE
Possible error in the implementation of GIoU in association.py

### ISSUE THREAD

**Issue by ak-tiwary** [noahcao/OC_SORT#64]
In line 53 of association.py the giou is computed as 

`giou = iou - (area_enclose - wh) / area_enclose`

However from the original [paper](https://arxiv.org/pdf/1902.09630.pdf) I believe the should actually be `(area_enclose - area_of_union)/area_enclose` since I believe `wh` is the area of the intersection in the code. Am I missing something?

**Comment by noahcao** [comment]
<img width="493" alt="Screen Shot 2022-11-18 at 12 09 02 AM" src="https://user-images.githubusercontent.com/17743251/202624216-c77e7fe9-bfc8-4367-9f65-f691f9d1ccf8.png">

Please refer to the calculation in the paper you send.

**Comment by ak-tiwary** [comment]
I'm sorry, but doesn't this code say exactly what I said? It says it should be (area(enclosing object) - area(union) )/ area(enclosing object) and not what the code is, which is (area(enclosing object) - area(intersection) )/(area(enclosing object))

**Comment by noahcao** [comment]
Thanks so much. yes, that's a bug. I have fixed it in the commit 2d34c67
