### ISSUE TITLE
Evaluate KITTI test

### ISSUE THREAD

**Issue by cuonga1cvp** [noahcao/OC_SORT#66]
Dear @noahcao ,
How you can evaluate the result of KITTI test set? I submit to KITTI tracking benchmark but it is not in right format.
Hope to receive your answer soon.
BRs,
cuong

**Comment by noahcao** [comment]
Please compare your output files with the format [here](https://github.com/noahcao/OC_SORT/tree/master/exps/permatrack_kitti_test).

**Comment by cuonga1cvp** [comment]
After run this code "python tools/run_ocsort_public.py  --hp --out_path kitti_test --dataset kitti --raw_results_path exps/permatrack_kitti_test" I got result on folder "kitti test". So the result for tracking is on folder "permatrack_kitti_test", not "kitti test" right?

**Comment by noahcao** [comment]
results in *permatrack_kitti_test* are from PermaTrack. We only use their detection results. The results from OC-SORT should be in your new created folder.

**Comment by cuonga1cvp** [comment]
yes. But how can you evaluate that result? I submit it to KITTI benchmark but they reply "Result: Tracker file not found: bb37d4b7aeae0f120874d54c9bbb5a05b42d41a8/data/0000.txt"
This is an example output from my created folder:
"0 6 Car -1 -1 -1 658.3400003471244 175.53999975 719.4199996528756 219.53000025 -1 -1 -1 -1000 -1000 -1000 -10 1"

**Comment by noahcao** [comment]
Are you putting the files in the correct folder hierarchy? I remember you should put the .txt files into a folder called "data"

**Comment by cuonga1cvp** [comment]
really? I only create a Zip file and inside is a folder called "kitti test" and inside that folder is .txt file

**Comment by cuonga1cvp** [comment]
I still got the same reply from KITTI benchmark. 
Can you look at my output and is it in right format?
"0 6 Car -1 -1 -1 658.3400003471244 175.53999975 719.4199996528756 219.53000025 -1 -1 -1 -1000 -1000 -1000 -10 1"
I also put my .txt files in folder called "data" too.
So how can you evaluate your tracking result on kitti?

**Comment by noahcao** [comment]
Format looks correct. My account can't submit anymore on KITTI server. I haven't submitted to KITTI for a long time. Could you try directly submit [this results](https://drive.google.com/file/d/1dpPMHV_ga55MdfN2NZgueYtW-2awpT1L/view?usp=share_link) ?

**Comment by noahcao** [comment]
I just tried the result .zip file linked above. It can be successfully evaluated. Please check the format with the reference from that file.

**Comment by cuonga1cvp** [comment]
"Result: Tracking data from tracker 86d3c420feb7769c399052439bde9be287d89e5d, sequence 0004 cannot be converted to the right format. Is data corrupted?"
I still got this reply from kitti when submit your result :(

**Comment by noahcao** [comment]
I truly can't understand the situation here now. Are you submitting the file to the right task?

But also, the warning information changed so the current file hierarchy is correct now. Maybe you should try to submit your results in the correct file organization.

**Comment by cuonga1cvp** [comment]
oh i see. I submit on wrong task. Sorry it's my first time.
Thank you a lot for your great work and helpfulness
