### ISSUE TITLE
where l can use the byte?

### ISSUE THREAD

**Issue by gyh420** [noahcao/OC_SORT#69]

**Comment by noahcao** [comment]
Set `use_byte=True` [here](https://github.com/noahcao/OC_SORT/blob/2d34c67d58f89b0762ce912c38f94746175e2903/trackers/ocsort_tracker/ocsort.py#L177)

**Comment by gyh420** [comment]
thank for your reply, when l  Set use_byte=True in ocsort.py, there have no change when l run python tools/run_ocsort.py -f exps/example/mot/yolox_x_ablation.py -c pretrained/bytetrack_ablation.pth.tar -b 1 -d 1 --fp16 --fuse --expn $exp_name. is still 74.0 of mota, why?
