### ISSUE TITLE
Ablation study

### ISSUE THREAD

**Issue by dyhBUPT** [noahcao/OC_SORT#71]
Hi, thanks for your great work.

I've tried to conduct ablation study of OOS/OCM/OCR on MOT17-val.
However, in my experiments, OOS doesn't work.

I turn off "OOS" by set `orig=True` in `class KalmanBoxTracker`:
```python
class KalmanBoxTracker(object):
    """
    This class represents the internal state of individual tracked objects observed as bbox.
    """
    count = 0

    def __init__(self, bbox, delta_t=3, orig=False):
        """
        Initialises a tracker using initial bounding box.

        """
        orig = True  # <= I added this line
        # define constant velocity model
        ...
```
And my results is (HOTA/MOTA/IDF1):
- with OOS: 66.341 / 74.504 / 77.874
- w/o  OOS: 66.442 / 74.665 / 77.864

Could you tell me if it is because of my mistakes or other reasons? Thanks!

**Comment by noahcao** [comment]
OOS has been deprecated, which is termed and used in the previous preprint version. Please use the latest code instead. Thanks.
