### ISSUE TITLE
is it possible to provide MOT20 track results?

### ISSUE THREAD

**Issue by ssbilakeri** [noahcao/OC_SORT#73]
I generated track results using OC-SORT, but facing problem when submitted results to motchallenge server. submission happens successfully but unable to get evaluation results. if you provide your results i can check the issue.

**Comment by noahcao** [comment]
We don't provide the output as it can be derived by running our provided code and scripts. typically, a common issue causing failing on motchallenge submission is that you include the .txt files in a subforlder before zipping them.
