### ISSUE TITLE
there is no dancetrack/yolox_x.py?

### ISSUE THREAD

**Issue by ZHuangyeei** [noahcao/OC_SORT#74]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/73516263/211278064-a455648c-f2bc-4669-9b70-bbc46c9bd073.png">

**Comment by gyh420** [comment]
find?

**Comment by ZHuangyeei** [comment]
you need to download here :https://github.com/Megvii-BaseDetection/YOLOX

**Comment by noahcao** [comment]
@ZHuangyeei gave the right answer. Sorry for the late reply. I am closing this issue as it has been solved.
