### ISSUE TITLE
Question about KF.predict

### ISSUE THREAD

**Issue by MattVAD** [noahcao/OC_SORT#75]
Hello and thank you for OCSort tracker. 

I have just noticed a different operation compared to SORT and DEEPSORT in the predict stage of the tracker. You added a condition on the time_since_update, if it is > 0, then the hit_freak of the tracker is initialized to 0. If on 1 frame we lose the detection, we must wait for the condition hit_freak > n_init before displaying the tracker. For old trackers, there is no such initialization of hit_freak parameter. Is there any interest in this modification? 
Thanks in advance.

**Comment by noahcao** [comment]
Hi there,

This operation is actually inherited from SORT or DeepSORT. This is called the `minimum hits` to allow to initialize a new track. You can find the same operation in [SORT](https://github.com/abewley/sort/blob/da0fe4d20ff3ca1c7bad3f746fa79e3c97421bf2/sort.py#L245) and [DeepSORT](https://github.com/nwojke/deep_sort/blob/280b8bdb255f223813ff4a8679f3e1321b08cdfc/deep_sort/track.py#L33) as well.
