### ISSUE TITLE
Please help me to understand the angle difference cost computation

### ISSUE THREAD

**Issue by ssbilakeri** [noahcao/OC_SORT#76]
Would you please explain me each line, im unable to understand 

   Y, X = speed_direction_batch(detections, previous_obs)
    inertia_Y, inertia_X = velocities[:,0], velocities[:,1]
    inertia_Y = np.repeat(inertia_Y[:, np.newaxis], Y.shape[1], axis=1)
    inertia_X = np.repeat(inertia_X[:, np.newaxis], X.shape[1], axis=1)
    diff_angle_cos = inertia_X * X + inertia_Y * Y
    diff_angle_cos = np.clip(diff_angle_cos, a_min=-1, a_max=1)
    diff_angle = np.arccos(diff_angle_cos)
    diff_angle = (np.pi /2.0 - np.abs(diff_angle)) / np.pi

    valid_mask = np.ones(previous_obs.shape[0])
    valid_mask[np.where(previous_obs[:,4]<0)]=0  
    valid_mask = np.repeat(valid_mask[:, np.newaxis], X.shape[1], axis=1)

    scores = np.repeat(detections[:,-1][:, np.newaxis], trackers.shape[0], axis=1)
    angle_diff_cost = (valid_mask * diff_angle) * vdc_weight
    angle_diff_cost = angle_diff_cost.T
    angle_diff_cost = angle_diff_cost * scores

**Comment by Stephen-Ning** [comment]
> inertia_Y

![1677228090817](https://user-images.githubusercontent.com/108001646/221132547-05ef5284-ef9f-484a-a908-3b5deb642663.jpg)
Hello! Where is this formula reflected in the code?

**Comment by Stephen-Ning** [comment]
> 请你解释一下每一行，我无法理解
> 
> Y, X = speed_direction_batch(detections, previous_obs) inertia_Y, inertia_X = velocities[:,0], velocities[:,1] inertia_Y = np.repeat(inertia_Y[:, np.newaxis], Y.shape[1], 轴=1) inertia_X = np.repeat(inertia_X[:, np.newaxis], X.shape[1], axis=1) diff_angle_cos = inertia_X * X + inertia_Y * Y diff_angle_cos = np.clip(diff_angle_cos, a_min=-1 , a_max=1) diff_angle = np.arccos(diff_angle_cos) diff_angle = (np.pi /2.0 - np.abs(diff_angle)) / np.pi
> 
> ```
> valid_mask = np.ones(previous_obs.shape[0])
> valid_mask[np.where(previous_obs[:,4]<0)]=0  
> valid_mask = np.repeat(valid_mask[:, np.newaxis], X.shape[1], axis=1)
> 
> scores = np.repeat(detections[:,-1][:, np.newaxis], trackers.shape[0], axis=1)
> angle_diff_cost = (valid_mask * diff_angle) * vdc_weight
> angle_diff_cost = angle_diff_cost.T
> angle_diff_cost = angle_diff_cost * scores
> ```

Do you understand?

**Comment by noahcao** [comment]
The key here is the calculation of `diff_angle` which is the difference of angles formed with x-axis in radian. This follows Eq9 in the appendix of the [paper](https://arxiv.org/pdf/2203.14360.pdf). The contribution of this angle difference term is weighted and summed up with the IoU cost to form the final cost matrix for association.
