### ISSUE TITLE
demo_track.py

### ISSUE THREAD

**Issue by moonnyeon** [noahcao/OC_SORT#78]
I made a Docker image as specified in the installation and ran the demo_track.py.

python tools/demo_track.py --demo_type video -f exps/example/mot/yolox_dancetrack_test.py -c pretrained/ocsort_dance_model.pth.tar --path videos/dance_demo.mp4 --fp16 --fuse --save_result --out_path demo_out.mp4

![image](https://user-images.githubusercontent.com/87063668/217785361-ef9cd6fb-8a7d-402b-88a7-05adc606b203.png)

![image](https://user-images.githubusercontent.com/87063668/217787929-df195e8a-3eb2-4dac-8446-a5dc04121545.png)

what should i do ?

**Comment by moonnyeon** [comment]
i solved by 
pip install --upgrade torchvision

**Comment by rlleshi** [comment]
Not really. That could install a version that isn't really compatible. 

Just make sure that you indeed have the torchvision version specified in the Dockerfile, namely `torchvision==0.10.1+cu111`. 

So sth like: `pip install torchvision==0.10.1+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html`
