### ISSUE TITLE
obsevation centric onlne smoothing what is the value of t in the equation 10 for virtual trajectory generation, Also which part of code defines this method ?

### ISSUE THREAD

**Issue by ssbilakeri** [noahcao/OC_SORT#81]

**Comment by upperblacksmith** [comment]
I think the part of code about obsevation centric onlne smoothing is not implement

**Comment by noahcao** [comment]
The OOS is defined in the customized version of [kalman filter](https://github.com/noahcao/OC_SORT/blob/master/trackers/ocsort_tracker/kalmanfilter.py). Also, I am refactoring the code to make it clean and we have renamed OOS as Observation-centric Re-Update now.
