### ISSUE TITLE
Reproduce the code

### ISSUE THREAD

**Issue by WMYYDREAM** [noahcao/OC_SORT#82]
After reading your readme and want to reproduce your paper, are there more detailed steps? At the same time, I also want to combine with YOLOV7? Thank you

**Comment by noahcao** [comment]
To reproduce the reported performance, you should just download the corresponding yolox detector weights and run the inference code, whose config files are already provided.

There is an example to incorporate other detectors, you can customize it yourself (there is [an example](https://github.com/noahcao/OC_SORT/issues/54)). Or you can use the oc-sort support in [mmtracking](https://github.com/open-mmlab/mmtracking).
