### ISSUE TITLE
2023 (CVPR) code version

### ISSUE THREAD

**Issue by VlSomers** [noahcao/OC_SORT#83]
Dear authors,

In your recent README update on the 02/28/2023, you mentioned "OC-SORT is accepted to CVPR 2023. We will update the code and paper soon.".
What is exactly the update you will release on the code? Is it a fix/update of the method itself, or a general refactoring of the code, or will the main code stay untouched?
I'm asking this question because I'm planning to integrate your method into my codebase, and I'm wondering if I should wait for a new version of your code before doing so.

Best

**Comment by noahcao** [comment]
Hi @VlSomers ,

In the new version of code to be released, the code will be refactored and some functions will be renamed to correspond to the update of the paper draft. The logic and functionality won't be changed. Therefore, if you are aiming to integrate OC-SORT to your own codebase, you can just use the current version. There will be no need to wait for the need release.
