### ISSUE TITLE
ORU/Virtual Trajectory code?

### ISSUE THREAD

**Issue by itberrios** [noahcao/OC_SORT#84]
Thanks for sharing your work!

I was wondering where the implementation of ORU and the virtual trajectory are located, I can't seem to find them.

**Comment by Postroggy** [comment]
@Gi-gigi @itberrios The ORU part is called in ocsort.py: [check here](https://github.com/noahcao/OC_SORT/blob/a9e24b6732b5d453b13399047207c0a515e0b8ae/trackers/ocsort_tracker/ocsort.py#L300)，and the virtual Trajectory is implemented in kalmanfilter.py in [chech here](https://github.com/noahcao/OC_SORT/blob/a9e24b6732b5d453b13399047207c0a515e0b8ae/trackers/ocsort_tracker/kalmanfilter.py#L466) through function `freeze()` and `unfreeze()`  
That's my Thinking, you can refer to. Hope it could help.

**Comment by itberrios** [comment]
Thanks!

**Comment by Postroggy** [comment]
已经收到您发送的邮件，有空处理了再联系您。郭跃琪

**Comment by Gi-gigi** [comment]
> @Gi-gigi @itberrios The ORU part is called in ocsort.py: [check here](https://github.com/noahcao/OC_SORT/blob/a9e24b6732b5d453b13399047207c0a515e0b8ae/trackers/ocsort_tracker/ocsort.py#L300)，and the virtual Trajectory is implemented in kalmanfilter.py in [chech here](https://github.com/noahcao/OC_SORT/blob/a9e24b6732b5d453b13399047207c0a515e0b8ae/trackers/ocsort_tracker/kalmanfilter.py#L466) through function `freeze()` and `unfreeze()` That's my Thinking, you can refer to. Hope it could help.

Thank you so much for your guidance! ! !
