### ISSUE TITLE
where is 'datasets/mot/annotations/train_half.json'

### ISSUE THREAD

**Issue by gw0522** [noahcao/OC_SORT#85]
An error is reported when running python3 tools/mix_data_ablation.py What is the file 'datasets/mot/annotations/train.json'and 'datasets/mot/annotations/train_half.json'

**Comment by gw0522** [comment]
(ocsort) lab509-2@lab509-2:/media/lab509-2/6t/gy/OC_SORT$ python3 tools/mix_data_{ablation/mot17/mot20}.py
python3: can't open file 'tools/mix_data_{ablation/mot17/mot20}.py': [Errno 2] No such file or directory
(ocsort) lab509-2@lab509-2:/media/lab509-2/6t/gy/OC_SORT$ python3 tools/mix_data_ablation.py
Traceback (most recent call last):
  File "tools/mix_data_ablation.py", line 17, in <module>
    mot_json = json.load(open('datasets/mot/annotations/train_half.json','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/mot/annotations/train_half.json'
(ocsort) lab509-2@lab509-2:/media/lab509-2/6t/gy/OC_SORT$ python3 tools/mix_data_test_mot17.py
Traceback (most recent call last):
  File "tools/mix_data_test_mot17.py", line 19, in <module>
    mot_json = json.load(open('datasets/mot/annotations/train.json','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/mot/annotations/train.json'
(ocsort) lab509-2@lab509-2:/media/lab509-2/6t/gy/OC_SORT$ python3 tools/mix_data_test_mot20.py
Traceback (most recent call last):
  File "tools/mix_data_test_mot20.py", line 17, in <module>
    mot_json = json.load(open('datasets/MOT20/annotations/train.json','r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MOT20/annotations/train.json'

**Comment by noahcao** [comment]
Those are annotation files converted from the raw annotation files for mot17/mot20. Please follow the instructions in [GET_STARTED.md](https://github.com/noahcao/OC_SORT/blob/master/docs/GET_STARTED.md) to prepare the dataset:
```
python3 tools/mix_data_{ablation/mot17/mot20}.py
