### ISSUE TITLE
OCSORT in other Language

### ISSUE THREAD

**Issue by Postroggy** [noahcao/OC_SORT#87]
May I ask if there is any plan for the author to write a C++ implementation of OCSORT code?

**Comment by Postroggy** [comment]
so I implemented the OC-SORT w/BYTE in C++, checkout out [this](https://github.com/Postroggy/OC_SORT_CPP)

**Comment by noahcao** [comment]
Thanks for the contribution!

**Comment by noahcao** [comment]
code merged. See deployment [readme](https://github.com/noahcao/OC_SORT/tree/master/deploy/OCSort/cpp)
