### ISSUE TITLE
ImportError: cannot import name 'COCODataset' from 'yolox.data'

### ISSUE THREAD

**Issue by Gi-gigi** [noahcao/OC_SORT#88]
when i run "`python3 tools/run_ocsort.py -f exps/example/mot/yolox_x_mix_det.py -c pretrained/bytetrack_x_mot17.pth.tar -b 1 -d 1 --fp16 --fuse --expn $exp_name`"  , occurring this problem. 
 
Please give me some pointers from the author, thank you！

**Comment by Gi-gigi** [comment]
Hello, author. I see that neither your ‘Train’ nor ‘Evaluation’ code involves Kalman. I am a CV novice, how can I run the code that has been OC-R by Kalman, that is, the part mentioned in the paper, and where can I run it?

**Comment by noahcao** [comment]
I can't reproduce the issue you are facing. Can you try the latest version of code? 

Also, the detector weights are renamed and can be found [here](https://github.com/noahcao/OC_SORT/blob/master/docs/MODEL_ZOO.md).
