### ISSUE TITLE
您好，deploy部分是否可以更新一下？

### ISSUE THREAD

**Issue by lmk123568** [noahcao/OC_SORT#89]
直接抄过去bytetrack的deploy。。。

**Comment by noahcao** [comment]
Yes. The current version is more like a placeholder for future modification. As the only difference between our implementation and ByteTrack is the tracker part, we inherited the most part of the deployment.

**Comment by noahcao** [comment]
I recently merged a C++ support from #96 , which may also be helpful to the community.

**Comment by noahcao** [comment]
The

**Comment by noahcao** [comment]
The C++ support is added [here](https://github.com/noahcao/OC_SORT/tree/master/deploy/OCSort/cpp). Thanks to @Postroggy, @phongans and their team for the contribution!
