### ISSUE TITLE
What is the meaning of the "inertia" parameter ?

### ISSUE THREAD

**Issue by flo-crn** [noahcao/OC_SORT#92]
Hi,
I'm trying to understand the different parameters of OC_SORT, especially the inertia parameter. What is its meaning and would it be a good parameter to play with in the case of objects with random moves (non constant velocity and acceleration) ?
Thank you for your response

**Comment by noahcao** [comment]
inertia is the weighting factor to keep the tendency of the previous movement (direction and speed). If you are solving random moves and you consider the acceleration can be very sharply changed, you may want a very small inertia or discard it as the inertia will prevent the object from changing the speed too suddenly.

**Comment by flo-crn** [comment]
Thank you very much, I will try this !
