### ISSUE TITLE
graphics card

### ISSUE THREAD

**Issue by Cagares** [noahcao/OC_SORT#93]
May I ask what model of graphics card your team used to train this model and how much memory is available. Recently, I have been trying to train my dataset and set the batch to 8. Using a v100, it shows that I need about 7 days to complete the training

**Comment by noahcao** [comment]
training the model is not necessary as we directly borrowed the detection model from [ByteTrack](https://github.com/ifzhang/ByteTrack). When training the detector as optional, we use 4xV100 GPUs.
