### ISSUE TITLE
How to test FPS of association step?

### ISSUE THREAD

**Issue by HanGuangXin** [noahcao/OC_SORT#95]
Hi there! How's it going? Currently, I'm testing the association speed of OC-SORT, which is reported to be 700+ FPS in the paper. However, when I run both the detection and association in an online manner, the FPS of the association step is only about 250. When I load detection results from local, the association speed is even much lower. I'm wondering what the correct steps are to test the association step to achieve the reported results (i.e., 700+ FPS). The hardware is V100 with intel xeon(R) silver 4212R CPU @ 2.40GHz x 48.

**Comment by noahcao** [comment]
Hi, when I tested the time latency for the association, I summed up the time consumed by the `predict` and `update` stages in the [tracker](https://github.com/noahcao/OC_SORT/blob/master/trackers/ocsort_tracker/ocsort.py). If you are loading the detections locally, you should not take the IO time into calculation which does not belong to the association operations.
